### ISSUE TITLE
plans for mozjpeg?

### ISSUE THREAD

**Issue by danleecreates** [dative/craft-do-forge-recipe#2]
Is there still plans to get mozjpeg into the recipe? Just tried installing manually and ran into issues.

This recipe was really helpful in getting going on Forge. Thanks!

**Comment by webrgp** [comment]
Sorry I've missed this, I will add to it.

**Comment by danleecreates** [comment]
Great! When can we expect this? We are about to do a massive content import and it would be amazing to have this in place to ext that extra 5% optimisation on images.
